# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Swedish spellchecker"
sv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Swedish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
sv = "TRANSLATE: A spellchecker for Swedish, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.sv"

[windows]
system_product_code = "{B9369728-6867-461A-9B93-031E5A71A644}_is1"
legacy_product_codes = [
    { value = "1D7005F8-D195-4760-8F46-646D2AD64BB9", kind = "nsis" },
    { value = "F8B27250-9843-4E98-998E-D5E544CFC2AF", kind = "nsis" }
]

[package.speller]
name = "Swedish"
version = "0.1.1"

[package.grammar]
name = "Swedish"
version = "0.1.0"

[package.tts-text-proc]
name = "Swedish"
version = "0.1.0"
