template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "swed1254"
__REPO__ = "lang-swe"
__UND2C__ = "sv"
__UNDEFINED__ = "Swedish"
__UND__ = "swe"
